
// This file has been generated by the GUI designer. Do not modify.

public partial class CryptoSec2FooterWidget
{
	private global::Gtk.HButtonBox hbuttonboxFooter;
	
	private global::Gtk.Button btnApplicationRelease;
	
	private global::Gtk.Button btnDocumentation;
	
	private global::Gtk.Button btnBugs;
	
	private global::Gtk.Button btnSourceCode;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget CryptoSec2FooterWidget
		global::Stetic.BinContainer.Attach (this);
		this.Name = "CryptoSec2FooterWidget";
		// Container child CryptoSec2FooterWidget.Gtk.Container+ContainerChild
		this.hbuttonboxFooter = new global::Gtk.HButtonBox ();
		this.hbuttonboxFooter.Name = "hbuttonboxFooter";
		this.hbuttonboxFooter.Homogeneous = true;
		this.hbuttonboxFooter.Spacing = 4;
		this.hbuttonboxFooter.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child hbuttonboxFooter.Gtk.ButtonBox+ButtonBoxChild
		this.btnApplicationRelease = new global::Gtk.Button ();
		this.btnApplicationRelease.CanFocus = true;
		this.btnApplicationRelease.Name = "btnApplicationRelease";
		this.btnApplicationRelease.UseUnderline = true;
		this.btnApplicationRelease.Label = global::Mono.Unix.Catalog.GetString ("Latest Release");
		this.hbuttonboxFooter.Add (this.btnApplicationRelease);
		global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxFooter [this.btnApplicationRelease]));
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbuttonboxFooter.Gtk.ButtonBox+ButtonBoxChild
		this.btnDocumentation = new global::Gtk.Button ();
		this.btnDocumentation.CanFocus = true;
		this.btnDocumentation.Name = "btnDocumentation";
		this.btnDocumentation.UseUnderline = true;
		this.btnDocumentation.Label = global::Mono.Unix.Catalog.GetString ("Documentation");
		this.hbuttonboxFooter.Add (this.btnDocumentation);
		global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxFooter [this.btnDocumentation]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbuttonboxFooter.Gtk.ButtonBox+ButtonBoxChild
		this.btnBugs = new global::Gtk.Button ();
		this.btnBugs.CanFocus = true;
		this.btnBugs.Name = "btnBugs";
		this.btnBugs.UseUnderline = true;
		this.btnBugs.Label = global::Mono.Unix.Catalog.GetString ("Bugs");
		this.hbuttonboxFooter.Add (this.btnBugs);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxFooter [this.btnBugs]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbuttonboxFooter.Gtk.ButtonBox+ButtonBoxChild
		this.btnSourceCode = new global::Gtk.Button ();
		this.btnSourceCode.CanFocus = true;
		this.btnSourceCode.Name = "btnSourceCode";
		this.btnSourceCode.UseUnderline = true;
		this.btnSourceCode.Label = global::Mono.Unix.Catalog.GetString ("Source Code");
		this.hbuttonboxFooter.Add (this.btnSourceCode);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxFooter [this.btnSourceCode]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.Add (this.hbuttonboxFooter);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
	}
}
