
// This file has been generated by the GUI designer. Do not modify.

public partial class CryptoSec2TitleWidget
{
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Image imgCryptoSec;
	
	private global::Gtk.Label lblCryptoSecTitle;
	
	private global::Gtk.Label lblCryptoSecModeInfoTitle;
	
	private global::Gtk.Label lblCryptoSecModeTitle;
	
	private global::Gtk.Image btnCryptoSecMode;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget CryptoSec2TitleWidget
		global::Stetic.BinContainer.Attach (this);
		this.Name = "CryptoSec2TitleWidget";
		// Container child CryptoSec2TitleWidget.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.imgCryptoSec = new global::Gtk.Image ();
		this.imgCryptoSec.Events = ((global::Gdk.EventMask)(260));
		this.imgCryptoSec.Name = "imgCryptoSec";
		this.imgCryptoSec.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("InGtkCryptoSec2.icons.keys.ico");
		this.hbox3.Add (this.imgCryptoSec);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.imgCryptoSec]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblCryptoSecTitle = new global::Gtk.Label ();
		this.lblCryptoSecTitle.Name = "lblCryptoSecTitle";
		this.lblCryptoSecTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>INCRYPTOSEC2</b>");
		this.lblCryptoSecTitle.UseMarkup = true;
		this.hbox3.Add (this.lblCryptoSecTitle);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblCryptoSecTitle]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		w2.Padding = ((uint)(5));
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblCryptoSecModeInfoTitle = new global::Gtk.Label ();
		this.lblCryptoSecModeInfoTitle.Name = "lblCryptoSecModeInfoTitle";
		this.lblCryptoSecModeInfoTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Running on : ");
		this.hbox3.Add (this.lblCryptoSecModeInfoTitle);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblCryptoSecModeInfoTitle]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblCryptoSecModeTitle = new global::Gtk.Label ();
		this.lblCryptoSecModeTitle.Name = "lblCryptoSecModeTitle";
		this.lblCryptoSecModeTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>ORACLE</b>");
		this.lblCryptoSecModeTitle.UseMarkup = true;
		this.lblCryptoSecModeTitle.UseUnderline = true;
		this.hbox3.Add (this.lblCryptoSecModeTitle);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblCryptoSecModeTitle]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
		w5.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnCryptoSecMode = new global::Gtk.Image ();
		this.btnCryptoSecMode.Events = ((global::Gdk.EventMask)(260));
		this.btnCryptoSecMode.Name = "btnCryptoSecMode";
		this.btnCryptoSecMode.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("InGtkCryptoSec2.icons.components.ico");
		this.hbox2.Add (this.btnCryptoSecMode);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnCryptoSecMode]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.Add (this.hbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
	}
}
