
// This file has been generated by the GUI designer. Do not modify.

public partial class CryptoConfigWidget
{
	private global::Gtk.Frame fraCryptoConfig;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.RadioButton rbnRsaCryptoProvider;
	
	private global::Gtk.RadioButton rbnDes3CryptoProvider;
	
	private global::Gtk.Label lblCryptoConfigTitle;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget CryptoConfigWidget
		global::Stetic.BinContainer.Attach (this);
		this.Name = "CryptoConfigWidget";
		// Container child CryptoConfigWidget.Gtk.Container+ContainerChild
		this.fraCryptoConfig = new global::Gtk.Frame ();
		this.fraCryptoConfig.Name = "fraCryptoConfig";
		this.fraCryptoConfig.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child fraCryptoConfig.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(4));
		this.GtkAlignment.TopPadding = ((uint)(4));
		this.GtkAlignment.RightPadding = ((uint)(4));
		this.GtkAlignment.BottomPadding = ((uint)(4));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.rbnRsaCryptoProvider = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("RSA Cryptography Provider"));
		this.rbnRsaCryptoProvider.TooltipMarkup = "RSA cryptography provider";
		this.rbnRsaCryptoProvider.CanFocus = true;
		this.rbnRsaCryptoProvider.Name = "rbnRsaCryptoProvider";
		this.rbnRsaCryptoProvider.DrawIndicator = true;
		this.rbnRsaCryptoProvider.UseUnderline = true;
		this.rbnRsaCryptoProvider.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox4.Add (this.rbnRsaCryptoProvider);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rbnRsaCryptoProvider]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.rbnDes3CryptoProvider = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("DES3 Cryptography Provider"));
		this.rbnDes3CryptoProvider.TooltipMarkup = "DES3 Cryptography Provider.";
		this.rbnDes3CryptoProvider.CanFocus = true;
		this.rbnDes3CryptoProvider.Name = "rbnDes3CryptoProvider";
		this.rbnDes3CryptoProvider.DrawIndicator = true;
		this.rbnDes3CryptoProvider.UseUnderline = true;
		this.rbnDes3CryptoProvider.Group = this.rbnRsaCryptoProvider.Group;
		this.vbox4.Add (this.rbnDes3CryptoProvider);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.rbnDes3CryptoProvider]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.GtkAlignment.Add (this.vbox4);
		this.fraCryptoConfig.Add (this.GtkAlignment);
		this.lblCryptoConfigTitle = new global::Gtk.Label ();
		this.lblCryptoConfigTitle.Name = "lblCryptoConfigTitle";
		this.lblCryptoConfigTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Cryptography Provider</b>");
		this.lblCryptoConfigTitle.UseMarkup = true;
		this.fraCryptoConfig.LabelWidget = this.lblCryptoConfigTitle;
		this.Add (this.fraCryptoConfig);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
	}
}
