
// This file has been generated by the GUI designer. Do not modify.

public partial class CryptoSecActionGroup
{
	private global::Gtk.Action OracleAction;

	public virtual void Build ()
	{
		// Action group CryptoSecActionGroup
		this.OracleAction = new global::Gtk.Action ("OracleAction", global::Mono.Unix.Catalog.GetString ("Oracle"), null, "Oracle_small");
		this.OracleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Oracle");
		this.Add (this.OracleAction, null);
	}
}
