
// This file has been generated by the GUI designer. Do not modify.

public partial class DatabaseConnectionSecWidget
{
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Frame frame2;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.TextView txtUserNameSec;
	
	private global::Gtk.Label lblUserNameSecTitle;
	
	private global::Gtk.Frame fraDatabaseUserPasswd;
	
	private global::Gtk.Alignment GtkAlignment2;
	
	private global::Gtk.TextView txtUserPasswdSec;
	
	private global::Gtk.Label lblDatabaseUserPasswdSec;
	
	private global::Gtk.Frame fraDatabaseServerSec;
	
	private global::Gtk.Alignment GtkAlignment3;
	
	private global::Gtk.TextView txtDatabaseServerSec;
	
	private global::Gtk.Label lblDatabaseServerSecTitle;
	
	private global::Gtk.Frame fraDatabaseConnectionStringSec;
	
	private global::Gtk.Alignment GtkAlignment4;
	
	private global::Gtk.TextView txtConnectionStringSec;
	
	private global::Gtk.Label lblDAtabaseConnectionStringSec;
	
	private global::Gtk.Label lblDatabaseConnectinSecTitile;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget DatabaseConnectionSecWidget
		global::Stetic.BinContainer.Attach (this);
		this.Name = "DatabaseConnectionSecWidget";
		// Container child DatabaseConnectionSecWidget.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(4));
		this.GtkAlignment.TopPadding = ((uint)(4));
		this.GtkAlignment.RightPadding = ((uint)(4));
		this.GtkAlignment.BottomPadding = ((uint)(4));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(4));
		this.GtkAlignment1.TopPadding = ((uint)(4));
		this.GtkAlignment1.RightPadding = ((uint)(4));
		this.GtkAlignment1.BottomPadding = ((uint)(4));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.txtUserNameSec = new global::Gtk.TextView ();
		this.txtUserNameSec.CanFocus = true;
		this.txtUserNameSec.Name = "txtUserNameSec";
		this.txtUserNameSec.Editable = false;
		this.txtUserNameSec.WrapMode = ((global::Gtk.WrapMode)(1));
		this.GtkAlignment1.Add (this.txtUserNameSec);
		this.frame2.Add (this.GtkAlignment1);
		this.lblUserNameSecTitle = new global::Gtk.Label ();
		this.lblUserNameSecTitle.Name = "lblUserNameSecTitle";
		this.lblUserNameSecTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>User Name</b>");
		this.lblUserNameSecTitle.UseMarkup = true;
		this.frame2.LabelWidget = this.lblUserNameSecTitle;
		this.vbox3.Add (this.frame2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame2]));
		w3.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fraDatabaseUserPasswd = new global::Gtk.Frame ();
		this.fraDatabaseUserPasswd.Name = "fraDatabaseUserPasswd";
		this.fraDatabaseUserPasswd.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child fraDatabaseUserPasswd.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(4));
		this.GtkAlignment2.TopPadding = ((uint)(4));
		this.GtkAlignment2.RightPadding = ((uint)(4));
		this.GtkAlignment2.BottomPadding = ((uint)(4));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.txtUserPasswdSec = new global::Gtk.TextView ();
		this.txtUserPasswdSec.CanFocus = true;
		this.txtUserPasswdSec.Name = "txtUserPasswdSec";
		this.txtUserPasswdSec.Editable = false;
		this.txtUserPasswdSec.WrapMode = ((global::Gtk.WrapMode)(1));
		this.GtkAlignment2.Add (this.txtUserPasswdSec);
		this.fraDatabaseUserPasswd.Add (this.GtkAlignment2);
		this.lblDatabaseUserPasswdSec = new global::Gtk.Label ();
		this.lblDatabaseUserPasswdSec.Name = "lblDatabaseUserPasswdSec";
		this.lblDatabaseUserPasswdSec.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Password</b>");
		this.lblDatabaseUserPasswdSec.UseMarkup = true;
		this.fraDatabaseUserPasswd.LabelWidget = this.lblDatabaseUserPasswdSec;
		this.vbox3.Add (this.fraDatabaseUserPasswd);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fraDatabaseUserPasswd]));
		w6.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fraDatabaseServerSec = new global::Gtk.Frame ();
		this.fraDatabaseServerSec.Name = "fraDatabaseServerSec";
		this.fraDatabaseServerSec.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child fraDatabaseServerSec.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(4));
		this.GtkAlignment3.TopPadding = ((uint)(4));
		this.GtkAlignment3.RightPadding = ((uint)(4));
		this.GtkAlignment3.BottomPadding = ((uint)(4));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.txtDatabaseServerSec = new global::Gtk.TextView ();
		this.txtDatabaseServerSec.CanFocus = true;
		this.txtDatabaseServerSec.Name = "txtDatabaseServerSec";
		this.txtDatabaseServerSec.Editable = false;
		this.txtDatabaseServerSec.WrapMode = ((global::Gtk.WrapMode)(1));
		this.GtkAlignment3.Add (this.txtDatabaseServerSec);
		this.fraDatabaseServerSec.Add (this.GtkAlignment3);
		this.lblDatabaseServerSecTitle = new global::Gtk.Label ();
		this.lblDatabaseServerSecTitle.Name = "lblDatabaseServerSecTitle";
		this.lblDatabaseServerSecTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Server</b>");
		this.lblDatabaseServerSecTitle.UseMarkup = true;
		this.fraDatabaseServerSec.LabelWidget = this.lblDatabaseServerSecTitle;
		this.vbox3.Add (this.fraDatabaseServerSec);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fraDatabaseServerSec]));
		w9.Position = 2;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fraDatabaseConnectionStringSec = new global::Gtk.Frame ();
		this.fraDatabaseConnectionStringSec.Name = "fraDatabaseConnectionStringSec";
		this.fraDatabaseConnectionStringSec.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child fraDatabaseConnectionStringSec.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(4));
		this.GtkAlignment4.TopPadding = ((uint)(4));
		this.GtkAlignment4.RightPadding = ((uint)(4));
		this.GtkAlignment4.BottomPadding = ((uint)(4));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.txtConnectionStringSec = new global::Gtk.TextView ();
		this.txtConnectionStringSec.CanFocus = true;
		this.txtConnectionStringSec.Name = "txtConnectionStringSec";
		this.txtConnectionStringSec.Editable = false;
		this.txtConnectionStringSec.WrapMode = ((global::Gtk.WrapMode)(1));
		this.GtkAlignment4.Add (this.txtConnectionStringSec);
		this.fraDatabaseConnectionStringSec.Add (this.GtkAlignment4);
		this.lblDAtabaseConnectionStringSec = new global::Gtk.Label ();
		this.lblDAtabaseConnectionStringSec.Name = "lblDAtabaseConnectionStringSec";
		this.lblDAtabaseConnectionStringSec.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Connection String</b>");
		this.lblDAtabaseConnectionStringSec.UseMarkup = true;
		this.fraDatabaseConnectionStringSec.LabelWidget = this.lblDAtabaseConnectionStringSec;
		this.vbox3.Add (this.fraDatabaseConnectionStringSec);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fraDatabaseConnectionStringSec]));
		w12.Position = 3;
		this.GtkAlignment.Add (this.vbox3);
		this.frame1.Add (this.GtkAlignment);
		this.lblDatabaseConnectinSecTitile = new global::Gtk.Label ();
		this.lblDatabaseConnectinSecTitile.Name = "lblDatabaseConnectinSecTitile";
		this.lblDatabaseConnectinSecTitile.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Database Connection Data</b>");
		this.lblDatabaseConnectinSecTitile.UseMarkup = true;
		this.frame1.LabelWidget = this.lblDatabaseConnectinSecTitile;
		this.Add (this.frame1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
	}
}
