
// This file has been generated by the GUI designer. Do not modify.

public partial class DatabaseLoginWidget
{
	private global::Gtk.Frame fraDatabaseLogin;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Button btnLogin;
	
	private global::Gtk.Label lblDatabaseServer;
	
	private global::Gtk.Label lblUserName;
	
	private global::Gtk.Label lblUserPasswd;
	
	private global::Gtk.Entry txtDatabaseServer;
	
	private global::Gtk.Entry txtUserName;
	
	private global::Gtk.Entry txtUserPasswd;
	
	private global::Gtk.Label GtkLabel1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget DatabaseLoginWidget
		global::Stetic.BinContainer.Attach (this);
		this.Name = "DatabaseLoginWidget";
		// Container child DatabaseLoginWidget.Gtk.Container+ContainerChild
		this.fraDatabaseLogin = new global::Gtk.Frame ();
		this.fraDatabaseLogin.Name = "fraDatabaseLogin";
		this.fraDatabaseLogin.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child fraDatabaseLogin.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(4));
		this.GtkAlignment.TopPadding = ((uint)(4));
		this.GtkAlignment.RightPadding = ((uint)(4));
		this.GtkAlignment.BottomPadding = ((uint)(4));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), true);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(4));
		this.table1.ColumnSpacing = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.btnLogin = new global::Gtk.Button ();
		this.btnLogin.TooltipMarkup = "Connect to database.";
		this.btnLogin.CanFocus = true;
		this.btnLogin.Name = "btnLogin";
		this.btnLogin.UseUnderline = true;
		this.btnLogin.Label = global::Mono.Unix.Catalog.GetString ("Login");
		global::Gtk.Image w1 = new global::Gtk.Image ();
		w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Menu);
		this.btnLogin.Image = w1;
		this.table1.Add (this.btnLogin);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnLogin]));
		w2.TopAttach = ((uint)(3));
		w2.BottomAttach = ((uint)(4));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.lblDatabaseServer = new global::Gtk.Label ();
		this.lblDatabaseServer.Name = "lblDatabaseServer";
		this.lblDatabaseServer.LabelProp = global::Mono.Unix.Catalog.GetString ("Server :");
		this.lblDatabaseServer.Justify = ((global::Gtk.Justification)(1));
		this.lblDatabaseServer.SingleLineMode = true;
		this.table1.Add (this.lblDatabaseServer);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblDatabaseServer]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.lblUserName = new global::Gtk.Label ();
		this.lblUserName.Name = "lblUserName";
		this.lblUserName.LabelProp = global::Mono.Unix.Catalog.GetString ("User Name :");
		this.lblUserName.SingleLineMode = true;
		this.table1.Add (this.lblUserName);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblUserName]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.lblUserPasswd = new global::Gtk.Label ();
		this.lblUserPasswd.Name = "lblUserPasswd";
		this.lblUserPasswd.LabelProp = global::Mono.Unix.Catalog.GetString ("Password :");
		this.table1.Add (this.lblUserPasswd);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblUserPasswd]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtDatabaseServer = new global::Gtk.Entry ();
		this.txtDatabaseServer.TooltipMarkup = "Database server name.";
		this.txtDatabaseServer.CanFocus = true;
		this.txtDatabaseServer.Name = "txtDatabaseServer";
		this.txtDatabaseServer.IsEditable = true;
		this.txtDatabaseServer.InvisibleChar = '●';
		this.table1.Add (this.txtDatabaseServer);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtDatabaseServer]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtUserName = new global::Gtk.Entry ();
		this.txtUserName.TooltipMarkup = "Database user name.";
		this.txtUserName.CanFocus = true;
		this.txtUserName.Name = "txtUserName";
		this.txtUserName.IsEditable = true;
		this.txtUserName.InvisibleChar = '●';
		this.table1.Add (this.txtUserName);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtUserName]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtUserPasswd = new global::Gtk.Entry ();
		this.txtUserPasswd.TooltipMarkup = "Database user password.";
		this.txtUserPasswd.CanFocus = true;
		this.txtUserPasswd.Name = "txtUserPasswd";
		this.txtUserPasswd.IsEditable = true;
		this.txtUserPasswd.Visibility = false;
		this.txtUserPasswd.InvisibleChar = '●';
		this.table1.Add (this.txtUserPasswd);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtUserPasswd]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table1);
		this.fraDatabaseLogin.Add (this.GtkAlignment);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Database LogIn</b>");
		this.GtkLabel1.UseMarkup = true;
		this.fraDatabaseLogin.LabelWidget = this.GtkLabel1;
		this.Add (this.fraDatabaseLogin);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
	}
}
